entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada

app_name = 'entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name = 'list_entrada'),
    path('new_entrada/', new_entrada, name = 'new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name = 'update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name = 'delete_entrada'),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida')),
    path('admin/', admin.site.urls),
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto

app_name = 'produto'
urlpatterns = [
    path('list_produto/', list_produto, name = 'list_produto'),
    path('new_produto/', new_produto, name = 'new_produto'),
    path('update_produto/<int:pk>/', update_produto, name = 'update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name = 'delete_produto'),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name = 'list_saida'),
    path('new_saida/', new_saida, name = 'new_saida'),
    path('update_saida/<int:pk>/', update_saida, name = 'update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name = 'delete_saida'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    template_name = 'index.html'
    context = {
        'mensagem': 'Bem vindo à aplicação estoqueWeb'
    }
    return render(request, template_name, context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,
  initial-scale=1.0">
  
    <title>Projeto Estoque</title>
    
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/jquery.dataTables.min.js' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="{% url 'index' %}">
            <img src={% static 'imagens/logo2.png' %} style="max-height: 90px" class="py-2" >
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{% url 'index' %}">
              <strong>Início</strong>
            </a>
            <a class="navbar-item" href="{% url 'produto:list_produto' %}">
              <strong>Produto</strong>
            </a>
            <a class="navbar-item" href="{% url 'entrada:list_entrada' %}">
              <strong>Entrada</strong>
            </a>
            <a class="navbar-item" href="{% url 'saida:list_saida' %}">
              <strong>Saída</strong>
            </a>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Registrar-se</strong>
                </a>
                <a class="button is-light">
                  <strong>Entrar</strong>
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
    <div class="box">
        <h1><strong>Estoque</strong></h1>
    </div>
    <div class="container">
        <div class="notification">
            {% block product %}{% endblock %}
        </div>
      </div>

    <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <strong>Projeto Estoque</strong> by Flávio Novaes. Apresentado como requisito para aprovação na disciplina <strong>Programação II</strong>.
          </p>
        </div>
      </footer>
</body>

<script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/js.js' %}"></script>
</html>

core/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto Estoque</title>
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
</head>

<body>
    <section class="hero is-large is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title is-1">
                    <span class="tag is-light is-medium">Projeto</span>Estoque 
                </h1>
                <h2 class="subtitle is-4">
                    <span class="tag is-light is-medium">Nome</span>Flávio Novaes
                </h2>
            </div>
        </div>
    </section>

    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <div class="columns has-text-centered">
                    <div class="column">
                        <h1 class ="title">Produtos</h1>
                        <h2 class="subtitle">Acesse a lista de produtos</h2>
                        <a class="button is-primary" href="{% url 'produto:list_produto' %}">Acessar</a>
                    </div>
                    <div class="column">
                        <h1 class="title">Entrada</h1>
                        <h2 class="subtitle">Acesse a entrada de produtos</h2>
                        <a class="button is-primary" href="{% url 'entrada:list_entrada' %}">Acessar</a>
                    </div>
                    <div class="column">
                        <h1 class="title">Saída</h1>
                        <h2 class="subtitle">Acesse a saída de produtos</h2>
                        <a class="button is-primary" href="{% url 'saida:list_saida' %}">Acessar</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <strong>Projeto Estoque</strong> by Flávio Novaes. Apresentado como requisito para aprovação na disciplina <strong>Programação II</strong>.
          </p>
        </div>
      </div>
    </footer>
</body>
</html>