estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida')),
    path('admin/', admin.site.urls),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name = 'list_saida'),
    path('new_saida/', new_saida, name = 'new_saida'),
    path('update_saida/<int:pk>/', update_saida, name = 'update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name = 'delete_saida'),
]

saida/models.py
from django.db import models
from produto.models import Produtos

# Create your models here.
class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete = models.CASCADE, verbose_name = 'Produto')
    quantidade = models.IntegerField('Quantidade', default = 0)
    criado = models.DateTimeField('Criado em', auto_now_add = True)
    modificado = models.DateTimeField('Modificado em', auto_now = True)
    
    def precoQuantidade(self):
        return self.preco * self.quantidade

saida/forms.py
from django.forms import ModelForm, TextInput, Select, NumberInput
from .models import Saidas

class SaidasForm(ModelForm):
    class Meta:
        model = Saidas
        fields = ['produto', 'quantidade']
        widgets = {
            'produto': Select(attrs={'class': 'select'}),
            'quantidade': NumberInput(attrs={'class': 'input'}),
        }

saida/views.py
from django.shortcuts import render, redirect
from .models import Saidas
from .forms import SaidasForm

def list_saida(request):
    saida = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
        'saidas':saida,
    }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidasForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'new_saida.html'
        context = {
            'form':SaidasForm(),
        }
        return render(request, template_name, context)

def update_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    quantidade = saida.quantidade
    print(f'==> {quantidade}')

    if request.method == 'POST':
        form = SaidasForm(request.POST, instance=saida)
        if form.is_valid():
            form.save(commit = False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'update_saida.html'
        context = {
            'form': SaidasForm(instance=saida),
            'pk': pk,
        }
        return render(request, template_name, context)

def delete_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    saida.produto.quantidade = saida.produto.quantidade + saida.quantidade
    saida.produto.save()
    saida.delete()
    return redirect('saida:list_saida')

saida/templates/list_saida.html
{% extends 'base.html' %}
{% block product %}
<p class="box has-text-centered">
    <strong>SAÍDAS</strong>
</p>
<div class="box">
    <a class="button is-primary" href="{% url 'saida:new_saida' %}">
        Novo
    </a>

    <table id="myTable" class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <th>Id</th>
                <th>Produto</th>
                <th>Quantidade</th>
                <th></th>
                <th></th>
            </tr>  
        </thead>
        <tbody>
            {% for saida in saidas %}
            <tr>
                <th>{{ saida.id }}</th>
                <td>{{ saida.produto }}</td>
                <td>{{ saida.quantidade }}</td>
                <td><a class="button is-primary" href="{% url 'saida:update_saida' saida.id %}">Alterar</a></td>
                <td><a class="button is-danger" href="{% url 'saida:delete_saida' saida.id %}">Deletar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}
</div>

saida/templates/new_saida.html
{% extends 'base.html' %}
{% block product %}
<div class="box has-text-centered">
    <p>
        <strong>NOVA SAÍDA</strong>
    </p>     
</div>

<div class="box">
    <form action="{% url 'saida:new_saida' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            <label class="label">{{ field.label }}</label>
            {% if field.name == 'produto' %}
            <div class="select">{{ field }}</div>
            {% else %}
            <div class="control">{{ field }}</div>
            {% endif %}
            {{ field.type }}
        </div>
        {% endfor %}
        <button class="button is-primary" type="submit">Salvar</button>
    </form>
    {% endblock %}
</div>

saida/templates/update_saida.html
{% extends 'base.html' %}
{% block product %}
<div class="box has-text-centered">
    <p>
        <strong>ALTERAR SAÍDA</strong>
    </p>     
</div>

<div class="box"> 
    <form action="{% url 'saida:update_saida' pk %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="field">
            <label class="label">{{ field.label }}</label>
            {% if field.name == 'produto' %}
            <div class="select">{{ field }}</div>
            {% else %}
            <div class="control">{{ field }}</div>
            {% endif %}
            {{ field.type }}
        </div>
        {% endfor %}
        <button class="button is-primary" type="submit">Salvar</button>
    </form>
    {% endblock %}
</div>